// packages/server/resources/js/components/multiagent/EpicDecompositionModal.vue
<template>
  <Modal
    :model-value="modelValue"
    :title="t('epicDecomposition.title')"
    class-name="!max-w-[640px] max-h-[85vh] flex flex-col"
    content-class="flex-1 min-h-0 overflow-y-auto"
    @update:model-value="onClose"
  >
    <div class="epic-decomp">
      <!-- Epic title -->
      <label class="ed-label" for="ed-title">{{ t('epicDecomposition.epicName') }}</label>
      <input
        id="ed-title"
        v-model="epicTitle"
        class="ed-input"
        :placeholder="t('epicDecomposition.epicNamePlaceholder')"
        maxlength="255"
      />

      <!-- PRD -->
      <label class="ed-label" for="ed-prd">{{ t('projects.decompose.prd_title') }}</label>
      <textarea
        id="ed-prd"
        v-model="prd"
        class="ed-textarea"
        :placeholder="t('projects.decompose.prd_placeholder')"
        rows="10"
        maxlength="50000"
      ></textarea>
      <div class="ed-charcount" :class="{ 'ed-charcount--over': prd.length > 50000 }">
        {{ prd.length }} / 50 000
      </div>

      <!-- Credential -->
      <label class="ed-label" for="ed-cred">{{ t('projects.decompose.credential') }}</label>
      <select id="ed-cred" v-model="credentialId" class="ed-input">
        <option value="" disabled>{{ t('projects.decompose.select_credential') }}</option>
        <option v-for="cred in credentials" :key="cred.id" :value="cred.id">
          {{ cred.name }} ({{ cred.auth_type }}){{ cred.is_default ? ' ★' : '' }}
        </option>
      </select>

      <p class="ed-hint">{{ t('epicDecomposition.decomposeWithAiHint') }}</p>
      <p v-if="error" class="ed-error">{{ error }}</p>
    </div>

    <template #footer>
      <div class="ed-actions">
        <button class="ed-btn ed-btn--ghost" @click="onClose">{{ t('common.cancel') }}</button>
        <!-- Single action: create the epic + launch its async decomposition. -->
        <button class="ed-btn ed-btn--primary" :disabled="!canDecompose" @click="onDecompose">
          <span v-if="isSubmitting" class="ed-spinner" aria-hidden="true" />
          {{ t('epicDecomposition.decomposeWithAi') }}
        </button>
      </div>
    </template>
  </Modal>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { storeToRefs } from 'pinia';
import Modal from '@/components/common/Modal.vue';
import { useCredentialsStore } from '@/stores/credentials';
import { api } from '@/composables/useApi';
import { useToast } from '@/composables/useToast';
import type { ApiResponse } from '@/types';

interface Props {
  projectId: string;
  modelValue: boolean;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  'update:modelValue': [value: boolean];
  // The async "Decompose with AI" run was launched: the epic exists (pending);
  // its sprints/tasks arrive later on the realtime `.epic.decomposition` signal.
  started: [];
}>();

const { t } = useI18n();
const toast = useToast();
const credentialsStore = useCredentialsStore();
const { credentials } = storeToRefs(credentialsStore);

const PRD_MIN_LENGTH = 20;
const PRD_MAX_LENGTH = 50000;

const epicTitle = ref('');
const prd = ref('');
const credentialId = ref('');
const isSubmitting = ref(false);
const error = ref<string | null>(null);

const canDecompose = computed(
  () =>
    epicTitle.value.trim().length > 0 &&
    prd.value.trim().length >= PRD_MIN_LENGTH &&
    prd.value.length <= PRD_MAX_LENGTH &&
    !!credentialId.value &&
    !isSubmitting.value,
);

// Single action: POST /projects/{id}/epics/decompose creates the epic up-front
// (pending) and spawns the decompose session. We don't await the plan — Show.vue
// surfaces the pending epic on `started` and reacts to the realtime completion.
async function onDecompose(): Promise<void> {
  if (!canDecompose.value) return;
  isSubmitting.value = true;
  error.value = null;
  try {
    await api.post<ApiResponse<{ status: string }>>(
      `/projects/${props.projectId}/epics/decompose`,
      {
        title: epicTitle.value.trim(),
        prd: prd.value,
        credential_id: credentialId.value,
      },
    );
    emit('started');
    onClose();
  } catch (e) {
    const msg =
      (e as { response?: { data?: { error?: { message?: string } } } })?.response?.data?.error
        ?.message ?? t('epicDecomposition.createFailed');
    error.value = msg;
    toast.error(msg);
  } finally {
    isSubmitting.value = false;
  }
}

function reset(): void {
  epicTitle.value = '';
  prd.value = '';
  credentialId.value = '';
  error.value = null;
  isSubmitting.value = false;
}

function onClose(): void {
  emit('update:modelValue', false);
}

// Reset + preload credentials (auto-selecting the default) whenever the modal opens.
watch(
  () => props.modelValue,
  async (open) => {
    if (!open) return;
    reset();
    if (credentialsStore.credentials.length === 0) {
      await credentialsStore.fetchCredentials();
    }
    if (!credentialId.value && credentialsStore.defaultCredential) {
      credentialId.value = credentialsStore.defaultCredential.id;
    }
  },
);
</script>

<style scoped>
.epic-decomp {
  display: flex;
  flex-direction: column;
  gap: 0.55rem;
  min-width: min(560px, 80vw);
}
.ed-label {
  font-size: 0.8rem;
  font-weight: 600;
  color: var(--text-secondary, #8b8ca0);
}
.ed-input,
.ed-textarea {
  width: 100%;
  padding: 0.55rem 0.7rem;
  border: 1px solid var(--border-color, #2a2d3a);
  border-radius: 8px;
  background: var(--bg-input, #1a1b26);
  color: var(--text-primary, #e6e6ef);
  font-size: 0.9rem;
}
.ed-textarea {
  resize: vertical;
  min-height: 9rem;
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 0.82rem;
  line-height: 1.5;
}
.ed-input:focus,
.ed-textarea:focus {
  outline: none;
  border-color: var(--accent-purple, #a855f7);
}
.ed-charcount {
  margin-top: -0.3rem;
  text-align: right;
  font-size: 0.7rem;
  color: var(--text-muted, #6b6d80);
  font-variant-numeric: tabular-nums;
}
.ed-charcount--over {
  color: var(--color-error, #ef4444);
}
.ed-hint {
  margin: 0.1rem 0 0;
  font-size: 0.78rem;
  color: var(--text-muted, #6b6d80);
}
.ed-error {
  color: var(--color-error, #ef4444);
  font-size: 0.8rem;
  margin: 0;
}
.ed-actions {
  display: flex;
  justify-content: flex-end;
  gap: 0.5rem;
}
.ed-btn {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  padding: 0.45rem 0.9rem;
  border-radius: 8px;
  font-size: 0.85rem;
  font-weight: 600;
  cursor: pointer;
  border: 1px solid transparent;
}
.ed-btn--ghost {
  background: transparent;
  border-color: var(--border-color, #2a2d3a);
  color: var(--text-secondary, #8b8ca0);
}
.ed-btn--primary {
  background: var(--accent-purple, #a855f7);
  color: #fff;
}
.ed-btn--primary:disabled {
  opacity: 0.5;
  cursor: default;
}
.ed-spinner {
  width: 0.8rem;
  height: 0.8rem;
  flex-shrink: 0;
  border-radius: 999px;
  border: 2px solid currentColor;
  border-top-color: transparent;
  animation: ed-spin 0.7s linear infinite;
}
@keyframes ed-spin {
  to {
    transform: rotate(360deg);
  }
}
@media (prefers-reduced-motion: reduce) {
  .ed-spinner {
    animation: none;
  }
}
</style>

// packages/mobile/src/components/multiagent/EpicDecompositionModal.tsx
/**
 * EpicDecompositionModal
 * Single-action PRD wizard: turn a product requirements doc into an epic.
 *
 * Mirrors the web `EpicDecompositionModal.vue` (the async flow): a single
 * "Decompose with AI" action POSTs to `/projects/{id}/epics/decompose`, which
 * creates the epic up-front in its `running` decomposition state and spawns a
 * sandboxed session. The sprints/tasks arrive later over the realtime
 * `.epic.decomposition` signal — so the modal does NOT await the plan; it just
 * fires `onStarted` once the run is launched, then closes.
 *
 * Distinct from the older two-step `DecomposeEpicScreen` (decompose → wait →
 * create-from-plan), which it supersedes for the epics board flow.
 */

import React, { memo, useCallback, useEffect, useState } from "react";
import {
  ActivityIndicator,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
import { MaterialIcons as Icon } from "@expo/vector-icons";
import { Modal } from "@/components/common";
import { t } from "@/i18n";
import { borderRadius, colors, spacing, typography } from "@/theme";
import { useCredentialsStore } from "@/stores/credentialsStore";
import { useEpicsStore } from "@/stores/epicsStore";
import type { Credential } from "@/stores/credentialsStore";

// ==================== CONSTANTS ====================

const PRD_MIN_LENGTH = 20;
const PRD_MAX_LENGTH = 50000;
const TITLE_MAX_LENGTH = 255;

// ==================== PROPS ====================

interface EpicDecompositionModalProps {
  visible: boolean;
  projectId: string;
  onClose: () => void;
  /**
   * The async "Decompose with AI" run was launched: the epic exists (running);
   * its sprints/tasks arrive later on the realtime `.epic.decomposition` signal.
   */
  onStarted?: () => void;
}

// ==================== CREDENTIAL OPTION ====================

interface CredentialOptionProps {
  credential: Credential;
  selected: boolean;
  disabled: boolean;
  onSelect: (id: string) => void;
}

const CredentialOption = memo(function CredentialOption({
  credential,
  selected,
  disabled,
  onSelect,
}: CredentialOptionProps) {
  const handlePress = useCallback(
    () => onSelect(credential.id),
    [credential.id, onSelect],
  );

  return (
    <TouchableOpacity
      style={[styles.credRow, selected && styles.credRowSelected]}
      onPress={handlePress}
      disabled={disabled}
      activeOpacity={0.8}
      accessibilityRole="radio"
      accessibilityState={{ selected, disabled }}
      accessibilityLabel={`${credential.name} (${credential.auth_type})`}
    >
      <Icon
        name={selected ? "radio-button-checked" : "radio-button-unchecked"}
        size={18}
        color={selected ? colors.accent.purple : colors.text.muted}
      />
      <Text
        style={[styles.credName, selected && styles.credNameSelected]}
        numberOfLines={1}
      >
        {credential.name}
      </Text>
      <Text style={styles.credMeta}>{credential.auth_type}</Text>
      {credential.is_default ? (
        <Icon name="star" size={14} color={colors.status.success} />
      ) : null}
    </TouchableOpacity>
  );
});

// ==================== MAIN MODAL ====================

export const EpicDecompositionModal = memo(function EpicDecompositionModal({
  visible,
  projectId,
  onClose,
  onStarted,
}: EpicDecompositionModalProps) {
  const credentials = useCredentialsStore((s) => s.credentials);
  const fetchCredentials = useCredentialsStore((s) => s.fetchCredentials);
  const getDefaultCredential = useCredentialsStore(
    (s) => s.getDefaultCredential,
  );
  const decomposeEpic = useEpicsStore((s) => s.decomposeEpic);

  const [epicTitle, setEpicTitle] = useState("");
  const [prd, setPrd] = useState("");
  const [credentialId, setCredentialId] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Reset + preload credentials (auto-selecting the default) whenever it opens.
  useEffect(() => {
    if (!visible) return;
    setEpicTitle("");
    setPrd("");
    setCredentialId("");
    setError(null);
    setIsSubmitting(false);

    const preload = async () => {
      if (useCredentialsStore.getState().credentials.length === 0) {
        await fetchCredentials();
      }
      const fallback = getDefaultCredential();
      if (fallback) setCredentialId(fallback.id);
    };
    void preload();
  }, [visible, fetchCredentials, getDefaultCredential]);

  const trimmedTitle = epicTitle.trim();
  const trimmedPrdLength = prd.trim().length;
  const prdOverLimit = prd.length > PRD_MAX_LENGTH;

  const canDecompose =
    trimmedTitle.length > 0 &&
    trimmedPrdLength >= PRD_MIN_LENGTH &&
    !prdOverLimit &&
    credentialId.length > 0 &&
    !isSubmitting;

  const handleDecompose = useCallback(async () => {
    if (
      trimmedTitle.length === 0 ||
      trimmedPrdLength < PRD_MIN_LENGTH ||
      prdOverLimit ||
      credentialId.length === 0 ||
      isSubmitting
    ) {
      return;
    }
    setIsSubmitting(true);
    setError(null);
    try {
      await decomposeEpic(projectId, {
        title: trimmedTitle,
        prd,
        credential_id: credentialId,
      });
      onStarted?.();
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : t("epicDecomp.failed"));
    } finally {
      setIsSubmitting(false);
    }
  }, [
    trimmedTitle,
    trimmedPrdLength,
    prdOverLimit,
    credentialId,
    isSubmitting,
    decomposeEpic,
    projectId,
    prd,
    onStarted,
    onClose,
  ]);

  const hasCredentials = credentials.length > 0;

  return (
    <Modal
      visible={visible}
      onClose={onClose}
      title={t("epicDecomp.title")}
      footer={
        <View style={styles.actions}>
          <TouchableOpacity
            style={styles.cancelBtn}
            onPress={onClose}
            activeOpacity={0.7}
            accessibilityRole="button"
          >
            <Text style={styles.cancelText}>{t("common.cancel")}</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={[styles.submitBtn, !canDecompose && styles.btnDisabled]}
            onPress={handleDecompose}
            disabled={!canDecompose}
            activeOpacity={0.85}
            accessibilityRole="button"
          >
            {isSubmitting ? (
              <ActivityIndicator size="small" color={colors.text.inverse} />
            ) : (
              <Icon name="auto-awesome" size={16} color={colors.text.inverse} />
            )}
            <Text style={styles.submitText}>
              {isSubmitting
                ? t("epicDecomp.submitting")
                : t("epicDecomp.submit")}
            </Text>
          </TouchableOpacity>
        </View>
      }
    >
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        keyboardShouldPersistTaps="handled"
        showsVerticalScrollIndicator={false}
      >
        {/* Epic title */}
        <Text style={styles.label}>{t("epicDecomp.epicName")}</Text>
        <TextInput
          style={styles.input}
          placeholder={t("epicDecomp.epicNamePlaceholder")}
          placeholderTextColor={colors.text.muted}
          value={epicTitle}
          onChangeText={setEpicTitle}
          editable={!isSubmitting}
          maxLength={TITLE_MAX_LENGTH}
          returnKeyType="next"
        />

        {/* PRD */}
        <Text style={styles.label}>{t("epicDecomp.prd")}</Text>
        <TextInput
          style={[styles.input, styles.textarea]}
          placeholder={t("epicDecomp.prdPlaceholder")}
          placeholderTextColor={colors.text.muted}
          value={prd}
          onChangeText={setPrd}
          editable={!isSubmitting}
          multiline
          textAlignVertical="top"
          maxLength={PRD_MAX_LENGTH}
        />
        <Text style={[styles.charCount, prdOverLimit && styles.charCountOver]}>
          {prd.length} / {PRD_MAX_LENGTH}
        </Text>

        {/* Credential */}
        <Text style={styles.label}>{t("epicDecomp.credential")}</Text>
        {hasCredentials ? (
          <View style={styles.credList}>
            {credentials.map((cred) => (
              <CredentialOption
                key={cred.id}
                credential={cred}
                selected={cred.id === credentialId}
                disabled={isSubmitting}
                onSelect={setCredentialId}
              />
            ))}
          </View>
        ) : (
          <View style={styles.noCredBox}>
            <Icon name="vpn-key-off" size={16} color={colors.text.secondary} />
            <Text style={styles.noCredText}>
              {t("epicDecomp.noCredential")}
            </Text>
          </View>
        )}

        <Text style={styles.hint}>{t("epicDecomp.hint")}</Text>

        {error ? (
          <View style={styles.errorRow}>
            <Icon name="error-outline" size={14} color={colors.status.error} />
            <Text style={styles.errorText}>{error}</Text>
          </View>
        ) : null}
      </ScrollView>
    </Modal>
  );
});

// ==================== STYLES ====================

const styles = StyleSheet.create({
  scroll: {
    // Cap height so the sheet stays usable with the keyboard up.
    maxHeight: 460,
  },
  scrollContent: {
    gap: spacing.xs,
    paddingBottom: spacing.sm,
  },
  label: {
    fontSize: typography.size.sm,
    fontWeight: "600",
    color: colors.text.secondary,
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
  },
  input: {
    backgroundColor: colors.bg.input,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.default,
    color: colors.text.primary,
    fontSize: typography.size.base,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  textarea: {
    ...typography.mono,
    minHeight: 150,
    fontSize: 13,
    lineHeight: 19,
    paddingTop: spacing.sm,
  },
  charCount: {
    textAlign: "right",
    fontSize: typography.size.xs,
    color: colors.text.muted,
    fontVariant: ["tabular-nums"],
    marginTop: 2,
  },
  charCountOver: {
    color: colors.status.error,
  },
  credList: {
    gap: spacing.xs,
  },
  credRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.bg.input,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.default,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  credRowSelected: {
    borderColor: colors.accent.purple,
    backgroundColor: `${colors.accent.purple}14`,
  },
  credName: {
    flex: 1,
    fontSize: typography.size.base,
    color: colors.text.primary,
  },
  credNameSelected: {
    color: colors.accent.purple,
    fontWeight: "600",
  },
  credMeta: {
    fontSize: typography.size.xs,
    color: colors.text.muted,
  },
  noCredBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.bg.input,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.default,
    padding: spacing.md,
  },
  noCredText: {
    flex: 1,
    fontSize: typography.size.sm,
    color: colors.text.secondary,
    lineHeight: 18,
  },
  hint: {
    fontSize: typography.size.xs,
    color: colors.text.muted,
    lineHeight: 17,
    marginTop: spacing.sm,
  },
  errorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: `${colors.status.error}18`,
    borderRadius: borderRadius.base,
    borderWidth: 1,
    borderColor: `${colors.status.error}40`,
    padding: spacing.sm,
    marginTop: spacing.sm,
  },
  errorText: {
    flex: 1,
    fontSize: typography.size.sm,
    color: colors.status.error,
  },
  actions: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  cancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: borderRadius.md,
    backgroundColor: colors.bg.input,
    borderWidth: 1,
    borderColor: colors.border.default,
    alignItems: "center",
  },
  cancelText: {
    fontSize: typography.size.base,
    fontWeight: "600",
    color: colors.text.secondary,
  },
  submitBtn: {
    flex: 2,
    flexDirection: "row",
    gap: spacing.xs,
    paddingVertical: 12,
    borderRadius: borderRadius.md,
    backgroundColor: colors.accent.purple,
    alignItems: "center",
    justifyContent: "center",
  },
  btnDisabled: {
    opacity: 0.5,
  },
  submitText: {
    fontSize: typography.size.base,
    fontWeight: "700",
    color: colors.text.inverse,
  },
});
