// packages/server/resources/js/components/multiagent/TokenBudgetPanel.vue
<template>
  <div class="token-budget">
    <header class="tb-header">
      <h4 class="tb-title">{{ t('projectsTokenbudget.title') }}</h4>
      <button
        class="tb-refresh"
        :class="{ spinning: store.isLoadingTokenBudget }"
        :disabled="store.isLoadingTokenBudget"
        :title="t('projectsTokenbudget.title')"
        @click="load"
      >
        ↻
      </button>
    </header>

    <!-- Loading (first fetch only — keeps prior data on refresh) -->
    <p v-if="store.isLoadingTokenBudget && !budget" class="tb-empty">…</p>

    <!-- Error -->
    <p v-else-if="loadError" class="tb-error">{{ t('projectsTokenbudget.loadError') }}</p>

    <!-- Empty: no token usage recorded yet -->
    <p v-else-if="budget && budget.tokens.used === 0 && budget.tokens.session_total === 0" class="tb-empty">
      {{ t('projectsTokenbudget.noUsage') }}
    </p>

    <template v-else-if="budget">
      <!-- Cost -->
      <div class="tb-cost">
        <span class="tb-cost-label">{{ t('projectsTokenbudget.cost') }}</span>
        <span
          class="tb-cost-value"
          :title="t('projectsTokenbudget.costTooltip', { model: budget.cost.pricing_model })"
        >
          {{ formatCost(budget.cost.estimated_usd, budget.cost.currency) }}
        </span>
      </div>

      <!-- Usage bar against the project budget -->
      <div class="tb-usage">
        <div class="tb-usage-head">
          <span>{{ t('projectsTokenbudget.used') }}</span>
          <span class="tb-usage-figures">
            {{ formatTokens(budget.tokens.used) }}
            <template v-if="budget.tokens.max">/ {{ formatTokens(budget.tokens.max) }}</template>
            <template v-else>· {{ t('projectsTokenbudget.unlimited') }}</template>
          </span>
        </div>
        <div v-if="budget.tokens.max" class="tb-bar" :class="{ 'is-reached': budget.tokens.limit_reached }">
          <div class="tb-bar-fill" :style="{ width: `${Math.min(100, budget.tokens.percent)}%` }" />
        </div>
        <div class="tb-usage-foot">
          <span v-if="budget.tokens.max">{{ t('projectsTokenbudget.percentUsed', { percent: budget.tokens.percent }) }}</span>
          <span v-if="budget.tokens.limit_reached" class="tb-limit-reached">
            {{ t('projectsTokenbudget.limitReached') }}
          </span>
        </div>
      </div>

      <!-- Input / output split + sessions -->
      <dl class="tb-grid">
        <div class="tb-stat">
          <dt>{{ t('projectsTokenbudget.input') }}</dt>
          <dd>{{ formatTokens(budget.tokens.input) }}</dd>
        </div>
        <div class="tb-stat">
          <dt>{{ t('projectsTokenbudget.output') }}</dt>
          <dd>{{ formatTokens(budget.tokens.output) }}</dd>
        </div>
        <div class="tb-stat">
          <dt>{{ t('projectsTokenbudget.sessionTotal') }}</dt>
          <dd>{{ formatTokens(budget.tokens.session_total) }}</dd>
        </div>
        <div class="tb-stat">
          <dt>{{ t('projectsTokenbudget.sessions') }}</dt>
          <dd>{{ budget.sessions_count }}</dd>
        </div>
      </dl>

      <p class="tb-pricing">
        {{ t('projectsTokenbudget.pricingModel') }}: <code>{{ budget.cost.pricing_model }}</code>
      </p>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useProjectsStore } from '@/stores/projects';

interface Props {
  projectId: string;
}

const props = defineProps<Props>();

const { t } = useI18n();
const store = useProjectsStore();

const loadError = ref(false);
const budget = computed(() => store.tokenBudget);

async function load(): Promise<void> {
  loadError.value = false;
  try {
    await store.fetchTokenBudget(props.projectId);
  } catch {
    loadError.value = true;
  }
}

// Fetch on mount and whenever the project changes.
watch(() => props.projectId, load, { immediate: true });

function formatTokens(value: number): string {
  return `${value.toLocaleString()} ${t('projectsTokenbudget.tokens')}`;
}

function formatCost(value: number, currency: string): string {
  const prefix = currency === 'USD' ? '$' : '';
  return `${prefix}${value.toFixed(4)}${prefix ? '' : ` ${currency}`}`;
}
</script>

<style scoped>
.token-budget {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.tb-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.tb-title {
  margin: 0;
  font-size: 13px;
  font-weight: 600;
  color: var(--text-primary);
}

.tb-refresh {
  background: none;
  border: none;
  color: var(--text-secondary);
  font-size: 14px;
  cursor: pointer;
  line-height: 1;
  transition: color 0.15s ease;
}

.tb-refresh:hover {
  color: var(--text-primary);
}

.tb-refresh.spinning {
  animation: tb-spin 0.8s linear infinite;
}

@keyframes tb-spin {
  to {
    transform: rotate(360deg);
  }
}

.tb-empty {
  font-size: 12px;
  color: var(--text-muted);
  text-align: center;
  padding: 12px 0;
}

.tb-error {
  font-size: 12px;
  color: var(--color-error, #ef4444);
  padding: 8px 0;
}

/* Cost */
.tb-cost {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  padding: 8px 10px;
  background-color: var(--bg-tertiary, var(--bg-secondary));
  border: 1px solid var(--border-color);
  border-radius: 6px;
}

.tb-cost-label {
  font-size: 12px;
  color: var(--text-secondary);
}

.tb-cost-value {
  font-size: 18px;
  font-weight: 700;
  color: var(--color-primary, #a855f7);
  font-variant-numeric: tabular-nums;
}

/* Usage bar */
.tb-usage {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.tb-usage-head,
.tb-usage-foot {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 11px;
  color: var(--text-secondary);
}

.tb-usage-figures {
  font-variant-numeric: tabular-nums;
  color: var(--text-primary);
}

.tb-bar {
  height: 6px;
  background-color: var(--bg-tertiary, var(--bg-secondary));
  border-radius: 3px;
  overflow: hidden;
}

.tb-bar-fill {
  height: 100%;
  background-color: var(--color-primary, #a855f7);
  transition: width 0.3s ease;
}

.tb-bar.is-reached .tb-bar-fill {
  background-color: var(--color-error, #ef4444);
}

.tb-limit-reached {
  color: var(--color-error, #ef4444);
  font-weight: 600;
}

/* Stats grid */
.tb-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px;
  margin: 0;
}

.tb-stat {
  display: flex;
  flex-direction: column;
  gap: 2px;
  padding: 6px 8px;
  background-color: var(--bg-tertiary, var(--bg-secondary));
  border-radius: 6px;
}

.tb-stat dt {
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: var(--text-muted);
}

.tb-stat dd {
  margin: 0;
  font-size: 12px;
  font-weight: 600;
  color: var(--text-primary);
  font-variant-numeric: tabular-nums;
}

.tb-pricing {
  margin: 0;
  font-size: 11px;
  color: var(--text-muted);
}

.tb-pricing code {
  color: var(--text-secondary);
}
</style>

// packages/mobile/src/components/multiagent/TokenBudgetPanel.tsx
/**
 * TokenBudgetPanel
 * Token cost + budget for a shared project (web parity:
 * components/multiagent/TokenBudgetPanel.vue). Presentational: it renders the
 * TokenBudget snapshot and a refresh affordance — fetching is owned by the
 * caller (projectsStore.fetchTokenBudget) so the panel stays testable and
 * reusable.
 */

import React, { memo } from "react";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { MaterialIcons as Icon } from "@expo/vector-icons";
import { borderRadius, colors, spacing, typography } from "@/theme";
import type { TokenBudget } from "@/types";

interface TokenBudgetPanelProps {
  budget: TokenBudget | null;
  isLoading: boolean;
  error?: boolean;
  onRefresh: () => void;
}

function formatTokens(value: number): string {
  return `${value.toLocaleString()} tokens`;
}

function formatCost(value: number, currency: string): string {
  const prefix = currency === "USD" ? "$" : "";
  return `${prefix}${value.toFixed(4)}${prefix ? "" : ` ${currency}`}`;
}

export const TokenBudgetPanel = memo(function TokenBudgetPanel({
  budget,
  isLoading,
  error = false,
  onRefresh,
}: TokenBudgetPanelProps) {
  // Empty when the project has no recorded usage yet (both the project-level
  // counter and the session-derived total are zero).
  const isEmpty =
    !!budget && budget.tokens.used === 0 && budget.tokens.session_total === 0;

  const percent = budget ? Math.min(100, budget.tokens.percent) : 0;

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>Token budget</Text>
        <TouchableOpacity
          onPress={onRefresh}
          disabled={isLoading}
          style={styles.refresh}
          accessibilityRole="button"
          accessibilityLabel="Refresh token budget"
        >
          <Icon
            name="refresh"
            size={18}
            color={isLoading ? colors.text.muted : colors.accent.purple}
          />
        </TouchableOpacity>
      </View>

      {/* First fetch keeps prior data on subsequent refreshes. */}
      {isLoading && !budget ? (
        <Text style={styles.muted}>Loading…</Text>
      ) : error ? (
        <Text style={styles.error}>Failed to load token budget.</Text>
      ) : isEmpty ? (
        <Text style={styles.muted}>No token usage recorded yet.</Text>
      ) : budget ? (
        <>
          {/* Estimated cost */}
          <View style={styles.costRow}>
            <Text style={styles.costLabel}>Estimated cost</Text>
            <Text style={styles.costValue}>
              {formatCost(budget.cost.estimated_usd, budget.cost.currency)}
            </Text>
          </View>

          {/* Usage against the project budget */}
          <View style={styles.usage}>
            <View style={styles.usageHead}>
              <Text style={styles.usageLabel}>Used</Text>
              <Text style={styles.usageFigures}>
                {formatTokens(budget.tokens.used)}
                {budget.tokens.max
                  ? ` / ${formatTokens(budget.tokens.max)}`
                  : " · unlimited"}
              </Text>
            </View>
            {budget.tokens.max ? (
              <View style={styles.bar}>
                <View
                  style={[
                    styles.barFill,
                    { width: `${percent}%` },
                    budget.tokens.limit_reached && styles.barFillReached,
                  ]}
                />
              </View>
            ) : null}
            <View style={styles.usageFoot}>
              {budget.tokens.max ? (
                <Text style={styles.mutedSmall}>
                  {budget.tokens.percent}% used
                </Text>
              ) : (
                <View />
              )}
              {budget.tokens.limit_reached ? (
                <Text style={styles.limitReached}>Limit reached</Text>
              ) : null}
            </View>
          </View>

          {/* Input / output split + sessions */}
          <View style={styles.grid}>
            <Stat label="Input" value={formatTokens(budget.tokens.input)} />
            <Stat label="Output" value={formatTokens(budget.tokens.output)} />
            <Stat
              label="Session total"
              value={formatTokens(budget.tokens.session_total)}
            />
            <Stat label="Sessions" value={`${budget.sessions_count}`} />
          </View>

          <Text style={styles.pricing}>
            Pricing model:{" "}
            <Text style={styles.code}>{budget.cost.pricing_model}</Text>
          </Text>
        </>
      ) : null}
    </View>
  );
});

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.stat}>
      <Text style={styles.statLabel}>{label}</Text>
      <Text style={styles.statValue}>{value}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.bg.card,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border.subtle,
    padding: spacing.lg,
    gap: spacing.md,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  title: {
    ...typography.h3,
    color: colors.text.primary,
  },
  refresh: { padding: spacing.xs },
  muted: { ...typography.bodySmall, color: colors.text.muted },
  mutedSmall: { ...typography.caption, color: colors.text.muted },
  error: { ...typography.bodySmall, color: colors.status.error },

  costRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  costLabel: { ...typography.bodySmall, color: colors.text.secondary },
  costValue: {
    ...typography.body,
    fontWeight: "700",
    color: colors.accent.cyan,
    fontVariant: ["tabular-nums"],
  },

  usage: { gap: spacing.xs },
  usageHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  usageLabel: { ...typography.bodySmall, color: colors.text.secondary },
  usageFigures: {
    ...typography.bodySmall,
    color: colors.text.primary,
    fontVariant: ["tabular-nums"],
  },
  bar: {
    height: 6,
    backgroundColor: colors.bg.input,
    borderRadius: borderRadius.full,
    overflow: "hidden",
  },
  barFill: {
    height: "100%",
    backgroundColor: colors.accent.purple,
    borderRadius: borderRadius.full,
  },
  barFillReached: { backgroundColor: colors.status.error },
  usageFoot: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  limitReached: { ...typography.caption, color: colors.status.error },

  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  stat: {
    flexBasis: "47%",
    flexGrow: 1,
    backgroundColor: colors.bg.input,
    borderRadius: borderRadius.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    gap: 2,
  },
  statLabel: { ...typography.caption, color: colors.text.muted },
  statValue: {
    ...typography.bodySmall,
    color: colors.text.primary,
    fontVariant: ["tabular-nums"],
  },

  pricing: { ...typography.caption, color: colors.text.muted },
  code: { color: colors.text.secondary, fontFamily: "SpaceMono_400Regular" },
});
